dependencies:
  flutter:
    sdk: flutter
  
  # المكتبات الأساسية لـ Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.0.2
  
  # مكتبات الميزات الإضافية
  image_picker: ^1.1.2
  record: ^5.1.0
  intl: ^0.19.0 # لتنسيق التواريخ (مثل وقت آخر ظهور)

flutter:
  uses-material-design: true
