name: Build Haway APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Clean Flutter Project
        run: |
          # إنشاء مشروع جديد مستقل لتجنب تعارض نسخ أندرويد الافتراضية
          flutter create haway_project
          # نقل ملف الـ main.dart الخاص بك إلى المجلد الجديد
          cp main.dart haway_project/lib/main.dart

      - name: Build APK (Release Mode)
        run: |
          cd haway_project
          flutter pub get
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: haway-release-apk
          path: haway_project/build/app/outputs/flutter-apk/app-release.apk
