name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Prepare Project Structure
        run: |
          # مسح ملفات الأندرويد القديمة إذا وُجدت
          rm -rf android/
          # إنشاء هيكلية المشروع
          mkdir -p lib
          mv main.dart lib/main.dart || true
          # إعادة إنشاء ملفات الأندرويد بنظام v2 الحديث
          flutter create --project-name haway_app .
          # وضع ملف الإعدادات في مكانه الصحيح
          mkdir -p android/app/
          cp google-services.json android/app/google-services.json
        
      - name: Build APK
        run: flutter build apk --release
